# Generated by Django 2.0.4 on 2018-07-16 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Airport',
            fields=[
                ('code', models.CharField(max_length=3, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=127)),
                ('city', models.CharField(max_length=127)),
                ('country', models.CharField(max_length=127)),
                ('elevation', models.IntegerField()),
                ('latitude', models.DecimalField(decimal_places=2, max_digits=4)),
                ('longitude', models.DecimalField(decimal_places=2, max_digits=5)),
            ],
        ),
    ]
